/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      keyframes: {
        spin: {
          from: { transform: 'rotate(0deg)' },
          to: { transform: 'rotate(360deg)' },
        },
      },
    },
  },
  plugins: [],
  safelist: [
    // Base color classes
    'from-pink-50',
    'from-purple-50',
    'from-emerald-50',
    'from-amber-50',
    'bg-pink-100',
    'bg-purple-100',
    'bg-emerald-100',
    'bg-amber-100',
    'bg-rose-50',
    'bg-violet-50',
    'bg-green-50',
    'bg-yellow-50',
    'border-pink-100',
    'border-purple-100',
    'border-emerald-100',
    'border-amber-100',
    'border-rose-50',
    'border-violet-50',
    'border-green-50',
    'border-yellow-50',
    'text-pink-800',
    'text-purple-800',
    'text-emerald-800',
    'text-amber-800',
    'text-pink-700',
    'text-purple-700',
    'text-emerald-700',
    'text-amber-700',
    'bg-pink-700',
    'bg-purple-700',
    'bg-emerald-700',
    'bg-amber-700',
    'hover:bg-pink-800',
    'hover:bg-purple-800',
    'hover:bg-emerald-800',
    'hover:bg-amber-800',
    'border-pink-800',
    'border-purple-800',
    'border-emerald-800',
    'border-amber-800',
    'from-pink-100',
    'from-purple-100',
    'from-emerald-100',
    'from-amber-100',
    'via-rose-50',
    'via-violet-50',
    'via-green-50',
    'via-yellow-50',
    'to-pink-100',
    'to-purple-100',
    'to-emerald-100',
    'to-amber-100',
    // Print variants
    'print:bg-pink-100',
    'print:bg-purple-100',
    'print:bg-emerald-100',
    'print:bg-amber-100',
    'print:bg-rose-50',
    'print:bg-violet-50',
    'print:bg-green-50',
    'print:bg-yellow-50',
    'print:text-pink-800',
    'print:text-purple-800',
    'print:text-emerald-800',
    'print:text-amber-800',
    'print:text-pink-700',
    'print:text-purple-700',
    'print:text-emerald-700',
    'print:text-amber-700',
  ],
};